name: "Lint"
on:
  push:
    branches:
      - "*"
  workflow_dispatch:
  pull_request:
    branches:
      - "main" 

jobs:
  ktlint:
    name: "Kotlin"
    runs-on: ubuntu-latest
    env:
      lintResultFilename: ktlint-result.txt
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3
      - name: Run Kotlin linter
        id: ktlint-check
        uses: musichin/ktlint-check@v1.2.1
        with:
          version: '0.46.0'
          reporter: plain?group_by_file,output=${{ env.lintResultFilename }}
          relative: true
          verbose: true
        continue-on-error: true
      - name: Kotlin linter result
        run: |
          cat ${{ env.lintResultFilename }}
          [ "${{ steps.ktlint-check.outcome }}" == "success" ] || exit 1
